Youtube source: https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=2

In [2]:
import torch
import numpy as np

In [2]:
torch.cuda.is_available()

False

In [3]:
if torch.cuda.is_available():
    # Get the number of CUDA devices
    num_devices = torch.cuda.device_count()
    print("Number of CUDA devices:", num_devices)

    # Iterate over each CUDA device
    for i in range(num_devices):
        # Get device properties
        device = torch.cuda.get_device_properties(i)
        print(f"Device {i}:")
        print(f"Name: {device.name}")
        print(f"Total memory: {device.total_memory / (1024**3):.2f} GB")
        print(f"Compute capability: {device.major}.{device.minor}")
else:
    print("CUDA is not available.")

CUDA is not available.


In [4]:
x = torch.rand(3)
x

tensor([0.1425, 0.7481, 0.3347])

# PyTorch Tutorial 02 - Tensor Basics

In [5]:
x = torch.empty(3)
x

tensor([0., 0., 0.])

In [6]:
x = torch.empty(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
x = torch.empty(2, 2, 2, 3)
x

tensor([[[[-3.2566e+37,  1.8315e-42,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])

In [8]:
x = torch.rand(2, 2)
x

tensor([[0.8265, 0.1102],
        [0.6508, 0.3877]])

In [9]:
x = torch.zeros(2, 2)
x

tensor([[0., 0.],
        [0., 0.]])

In [10]:
x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

In [12]:
x = torch.ones(2, 2)
x.dtype

torch.float32

In [13]:
x = torch.ones(2, 2, dtype=torch.int)
# dtype = torch.double / torch.float16 / 
x.dtype

torch.int32

In [15]:
x = torch.ones(2, 2, dtype=torch.float16)
x.size()

torch.Size([2, 2])

In [16]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [17]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print("x:", x)
print("y:", y)

x: tensor([[0.1763, 0.6954],
        [0.7611, 0.5027]])
y: tensor([[0.7580, 0.1430],
        [0.7312, 0.1715]])


In [18]:
z = x + y
z

tensor([[0.9343, 0.8384],
        [1.4923, 0.6742]])

In [20]:
z = torch.add(x,y)
z

tensor([[0.9343, 0.8384],
        [1.4923, 0.6742]])

In [21]:
y.add_(x)
y

tensor([[0.9343, 0.8384],
        [1.4923, 0.6742]])

In [24]:
z = x - y
z

tensor([[-0.7580, -0.1430],
        [-0.7312, -0.1715]])

In [25]:
z = torch.sub(x, y)
z

tensor([[-0.7580, -0.1430],
        [-0.7312, -0.1715]])

In [26]:
z = x * y
z

tensor([[0.1647, 0.5830],
        [1.1358, 0.3389]])

In [27]:
z = torch.mul(x, y)
z

tensor([[0.1647, 0.5830],
        [1.1358, 0.3389]])

In [28]:
y.mul_(x)

tensor([[0.1647, 0.5830],
        [1.1358, 0.3389]])

In [31]:
z = x / y
z

tensor([[1.0703, 1.1928],
        [0.6701, 1.4833]])

In [33]:
z = torch.div(x, y)
z

tensor([[1.0703, 1.1928],
        [0.6701, 1.4833]])

In [34]:
x = torch.rand(5, 3)
x

tensor([[0.7752, 0.6711, 0.0440],
        [0.9599, 0.1368, 0.3040],
        [0.8819, 0.7473, 0.6045],
        [0.4483, 0.9362, 0.5687],
        [0.2761, 0.6541, 0.1963]])

In [35]:
x[:, 0]

tensor([0.7752, 0.9599, 0.8819, 0.4483, 0.2761])

In [36]:
x[1,:]

tensor([0.9599, 0.1368, 0.3040])

In [37]:
x[1,1]

tensor(0.1368)

In [38]:
x[1,1].item()

0.1368398666381836

In [39]:
x = torch.rand(4, 4)
y = x.view(16)

print("X:", x)
print("y:", y)

X: tensor([[0.6627, 0.6367, 0.9733, 0.8240],
        [0.2312, 0.6408, 0.0593, 0.1480],
        [0.7254, 0.2426, 0.7091, 0.0052],
        [0.5064, 0.9987, 0.3346, 0.3855]])
y: tensor([0.6627, 0.6367, 0.9733, 0.8240, 0.2312, 0.6408, 0.0593, 0.1480, 0.7254,
        0.2426, 0.7091, 0.0052, 0.5064, 0.9987, 0.3346, 0.3855])


In [41]:
print(x.view(-1, 8))

print(x.view(-1, 8).size())

tensor([[0.6627, 0.6367, 0.9733, 0.8240, 0.2312, 0.6408, 0.0593, 0.1480],
        [0.7254, 0.2426, 0.7091, 0.0052, 0.5064, 0.9987, 0.3346, 0.3855]])
torch.Size([2, 8])


In [43]:
# From torch to numpy
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [44]:
b = a.numpy()

print(b)

print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [45]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [46]:
b

# a and b share memory so it is shallow copy. It occurs when we use CPU. But if we work with GPU it wont be like that

array([2., 2., 2., 2., 2.], dtype=float32)

In [47]:
# From numpy to torch
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [48]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [52]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [54]:
############ NOTE ############ 

### Numpy operations handle only with CPU tensors not with GPU tensors

In [3]:
x = torch.ones(5, requires_grad=True)
x

# This requires_grad=True param tells that later when we do optimization tasks torch will calculate gradients

tensor([1., 1., 1., 1., 1.], requires_grad=True)