In [1]:
import numpy as np
import pandas as pd

In [2]:
# A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.values.tolist()

[0.25, 0.5, 0.75, 1.0]

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data.index.values

array([0, 1, 2, 3], dtype=int64)

In [7]:
print(data[1])

print('\n')
print(data[1:3])

0.5


1    0.50
2    0.75
dtype: float64


while the NumPy array has an implicitly defined integer index used
to access the values, the Pandas Series has an explicitly defined index associated with
the values. This explicit index definition gives the Series object additional capabilities. For
example, the index need not be an integer, but can consist of values of any desired
type.

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
print("data['b'] = ", data['b'])

print('\n')
print("data[1] = ", data[1])

data['b'] =  0.5


data[1] =  0.5


In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [11]:
print("data[5] = ", data[5])

print('\n')
print("data[1] gives error. As there is no index such as 1 in our newly implemented index set")

data[5] =  0.5


data[1] gives error. As there is no index such as 1 in our newly implemented index set


#### Applications in a small example

In [12]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

population = pd.Series(population_dict)

population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [13]:
print("population['California'] = ", population['California'])

print('\n')
print("population['California':'Illinois'] = ", population['California':'Illinois'])

population['California'] =  38332521


population['California':'Illinois'] =  California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


########################################

General structure of constructing Series objects

#### pd.Series(data, index=index)

In [14]:
# 1st approach

pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [15]:
# 2nd approach

pd.Series([0.25, 0.5, 0.75, 1.0],
          index=['a', 'b', 'c', 'd'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [16]:
# 3rd approach

pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [17]:
# 4th approach

pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [18]:
# 5th approach
# limiting the output data using index argument

pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

### Pandas DataFrame Object 

In [19]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area_dict

{'California': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

#### Pandas Series

In [20]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

#### Pandas Data Frame

In [21]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [22]:
print(states.index)

print('\n')
print(states.index.values)

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')


['California' 'Texas' 'New York' 'Florida' 'Illinois']


In [23]:
print(states.columns)

print('\n')
print("states.columns.values = ", states.columns.values)
print("states.columns.tolist() = ", states.columns.tolist())

Index(['population', 'area'], dtype='object')


states.columns.values =  ['population' 'area']
states.columns.tolist() =  ['population', 'area']


#### DataFrame as specialized dictionary

In [24]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

##### Constructing DataFrame objects

In [25]:
# From a single Series object. 
# using columns like cbind in R

pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [26]:
# From a list of dicts.

data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
 
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [27]:
# From a list of dicts.

# pd.DataFrame([{1st row}, {2nd row}, ...])
# using rows like rbind in R

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [28]:
# From a dictionary of Series objects.

# pd.DataFrame({1st column : col_name, 2nd column : col_name ,  ...})
# using columns like cbind in R

pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [29]:
# From a two-dimensional NumPy array

# pd.DataFrame(data, col_names, index)

pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.309365  0.383632
b  0.594999  0.204507
c  0.109737  0.881443

In [30]:
# From a NumPy structured array.

A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
print('A =', A)

pd.DataFrame(A)

A = [(0, 0.) (0, 0.) (0, 0.)]


A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

In [31]:
ind = pd.Index([2, 3, 5, 7, 11])

ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [32]:
print("ind[1] =          ", ind[1])

print("ind[::2] =        ", ind[::2])

ind[1] =           3
ind[::2] =         Int64Index([2, 5, 11], dtype='int64')


In [33]:
# Index objects also have many of the attributes familiar from NumPy arrays:

print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [34]:
# One difference between Index objects and NumPy arrays is that indices are immutable — that is, they cannot be 
# modified via the normal means:

print("The following code gives an error: \n       ind[1] = 0 ")

The following code gives an error: 
       ind[1] = 0 


#### Index as ordered set

In [35]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

print("indA = ", indA)
print("indB = ", indB)

indA =  Int64Index([1, 3, 5, 7, 9], dtype='int64')
indB =  Int64Index([2, 3, 5, 7, 11], dtype='int64')


In [36]:
# intersection

print(indA & indB )

# an equivalent code
print(indA.intersection(indB))

Int64Index([3, 5, 7], dtype='int64')
Int64Index([3, 5, 7], dtype='int64')


C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\1269607476.py:3: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  print(indA & indB )


In [37]:
# union

indA | indB 

C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\468489857.py:3: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  indA | indB


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [38]:
# symmetric difference

indA ^ indB 

C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\2056130902.py:3: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  indA ^ indB


Int64Index([1, 2, 9, 11], dtype='int64')

### Data Indexing and Selection

In [39]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [40]:
print("data['b'] =", data['b'])

print('\n')
print("data[1] =", data[1])

data['b'] = 0.5


data[1] = 0.5


In [41]:
# We can also use dictionary-like Python expressions and methods to examine the keys/indices and values:

'a' in data

True

In [42]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
data.items

<bound method Series.items of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [44]:
list(data.items())

# row-wise output

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [45]:
# Adding and editing a new / an existing values

data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### Slicing

In [46]:
# slicing by explicit index

data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [47]:
# slicing by implicit integer index

data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [48]:
# masking

data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [49]:
# fancy indexing
 
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

##### Indexers: loc, iloc, and ix

In [50]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [51]:
# explicit index when indexing
 
data[1]

'a'

In [52]:
# implicit index when slicing

data[1:3]

3    b
5    c
dtype: object

In [53]:
# First, the loc attribute allows indexing and slicing that always references the explicit index:

# data.loc[1] -> REFERS TO THE INDEX THAT WE NEWLY APPLIED, AND RETURNS CORRESPONDING DATA VALUES TO BASED ON THAT
# NEW INDEX SET

print(data.loc[1])

print('\n')
print(data.loc[1:3])

a


1    a
3    b
dtype: object


In [54]:
# The iloc attribute allows indexing and slicing that always references the implicit Python-style index:

# data.iloc[1] -> REFERS TO THE IMPLICIT THAT PYTHON-STYLE / PYTHON BUILT-IN INDEX AND RETURNS VALUES BASED ON THAT INSTEAD
# OF USING OUR NEWLY IMPLEMENTED NEW INDEX SET

print(data.iloc[1])

print('\n')
print(data.iloc[1:3])

b


3    b
5    c
dtype: object


#### A small example

In [55]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})

pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})

data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [56]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [57]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [58]:
data.area is data['area']

True

Though this is a useful shorthand **[ data.area is data['area'] ]**, keep in mind that it does not work for all cases!
For example, if the column names are not strings, or if the column names conflict
with methods of the DataFrame, this attribute-style access is not possible. For example, the DataFrame has a pop() method, so data.pop will point to this rather than the
"pop" column:


In [59]:
data.pop is data['pop']

False

In [60]:
data.pop

<bound method DataFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [61]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

if we have a data frame, called data with 3 column, namely A, B, C. Then if we apply pop() function with an input value of any column name then, this function just removes this column and saves it in a temporary memory so that it can be used 

column_B = data.pop('B')

column_B

In [62]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### DataFrame as two-dimensional array

In [63]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [64]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [65]:
# taking out row-wise data

data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [66]:
# taking out column-wise data

data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

#### IMPORTANT

In [67]:
# data.iloc[row, column]
# Using Python built-in index

data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [68]:
# data.loc[row, column]
# Using newly implemented index set by ourselves

data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

##### The ix indexer allows a hybrid of these two approaches:

But this approach has been deprecated in recent versions of pandas and has been removed since version 1.0.0

In [69]:
# data.ix[:3, :'pop']

print("data.ix[:3, :'pop'] gives an Error")

data.ix[:3, :'pop'] gives an Error


In [70]:
# Logical applications

data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [71]:
# Editing a value cell in a data frame

data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [72]:
# returning / selecting columns from a data set

data[['area','pop']]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [73]:
# returning / selecting rows from a data set

data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [74]:
# returning / selecting rows from a data set

data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [75]:
# Logical operations usage

data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

### Operating on Data in Pandas
##### Ufuncs: Index Preservation

In [76]:
rng = np.random.RandomState(42)

ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [77]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])

df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [78]:
# numpy.exponent(values)

np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [79]:
# apply a formula to the whole data frame 

np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [80]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [81]:
# The resulting array contains the union of indices of the two input arrays, which we
# could determine using standard Python set arithmetic on these indices:

area.index | population.index

C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\1983580578.py:4: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [82]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

print('A:')
print(A)

print('\n')
print('B:')
print(B)

A + B

A:
0    2
1    4
2    6
dtype: int64


B:
1    1
2    3
3    5
dtype: int64


0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

If using NaN values is not the desired behavior, we can modify the fill value using
appropriate object methods in place of the operators. For example, calling A.add(B)
is equivalent to calling A + B, but allows optional explicit specification of the fill value
for any elements in A or B that might be missing:

In [83]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

#### Index alignment in DataFrame

In [84]:
# rng.randint(start, end, Number or Matrix)

A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))

A

A   B
0  1  11
1  5   1

In [85]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))

B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [86]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

Notice that indices are aligned correctly irrespective of their order in the two objects,
and indices in the result are sorted. As was the case with Series, we can use the associated object’s arithmetic method and pass any desired fill_value to be used in place
of missing entries. Here we’ll fill with the mean of all values in A (which we compute
by first stacking the rows of A):

In [87]:
A

A   B
0  1  11
1  5   1

In [88]:
A.stack()

0  A     1
   B    11
1  A     5
   B     1
dtype: int32

In [89]:
A.stack().mean()

4.5

In [90]:
fill = A.stack().mean()    # fill = 8.5

A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

### Full list of operators & functions on a Table 3-1: Python operator Pandas method(s)

In [91]:
# rng.randint(end, Number or Matrix)     if start is not mentioned then it is taken as 0

A = rng.randint(10, size=(3, 4))

A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [92]:
# row wise math operations

A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [93]:
# PAY ATTENTION TO THE COLUMN NAMING APPROACH 

df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [94]:
# row wise math operations

df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [95]:
# If you would instead like to operate column-wise, you can use the object methods 
# mentioned earlier, while specifying the axis keyword:

# column wise math operations

df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [96]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [97]:
# re-iteration of values if the length of vectors are not the same

df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

### Handling Missing Data

In [98]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [99]:
# due to the missing data operations similar to the following can not be performed

# vals1.sum()

print("vals1.sum() gives an error")

vals1.sum() gives an error


In [100]:
np.nan

nan

In [101]:
None == np.nan

False

In [102]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [103]:
1 + np.nan

nan

In [104]:
print("1 + None -> gives an error")

1 + None -> gives an error


In [105]:
0 * np.nan

nan

In [106]:
# as we have nan value, we cant compare the values, as this nan value can be the lowest or the highest values as well

vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [107]:
# we can handle with this nan values using those functions first

# Also pay attention to the construction of a vector

np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

NaN and None both have their place, and Pandas is built to handle the two of them
nearly interchangeably, converting between them where appropriate:

In [108]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

##### For types that don’t have an available sentinel value, Pandas automatically type-casts when NA values are present. For example, if we set a value in an integer array to np.nan, it will automatically be upcast to a floating-point type to accommodate the NA: Look at the code above & below


In [109]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [110]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

#### Table 3-2. Pandas handling of NAs by type

#### Operating on Null Values

isnull() - Generate a Boolean mask indicating missing values

notnull() - Opposite of isnull()

dropna() - Return a filtered version of the data

fillna() - Return a copy of the data with missing values filled or imputed

In [111]:
data = pd.Series([1, np.nan, 'hello', None])

In [112]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [113]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [114]:
data.dropna()

0        1
2    hello
dtype: object

In [115]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [116]:
# By default, dropna() will drop all rows in which any null value is present:

df.dropna()

0    1  2
1  2.0  3.0  5

In [117]:
df.dropna(axis='columns')

# the same result 
# df.dropna(axis=1)

2
0  2
1  5
2  6

In [118]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [119]:
# The default is how='any', such that any row or column (depending on the axis keyword) 
# containing a null value will be dropped. You can also specify how='all', which
# will only drop rows/columns that are all null values:

df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [120]:
df.dropna(axis='columns', how='any')

2
0  2
1  5
2  6

In [121]:
# For finer-grained control, the thresh parameter lets you specify A MINIMUM NUMBER
# OF NON-NULL VALUES for the row/column to be kept:

df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [122]:
# pd.Series([data list], index = list(index_name))

data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [123]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [124]:
# forward-fill

data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [125]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [126]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [127]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [128]:
df.fillna(method='ffill' #, axis=0
         )

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  2.0  4.0  6 NaN

#### Hierarchical Indexing
A Multiply Indexed Series

In [129]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [130]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [131]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [132]:
# The better way: Pandas MultiIndex

index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [133]:
# dataset.reindex(new index style)

pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [134]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [135]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [136]:
pop_df.unstack().unstack()

California  New York     Texas
2000    33871648  18976457  20851820
2010    37253956  19378102  25145561

In [137]:
pop_df.T

California  New York     Texas
2000    33871648  18976457  20851820
2010    37253956  19378102  25145561

In [138]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [139]:
# we might want to add another column of demographic data for each state at each year
# (say, population under 18); with a MultiIndex this is as easy as adding another column to the DataFrame:

# Creating a new pandas Data Frame

pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [140]:
f_u18 = pop_df['under18'] / pop_df['total']

f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [141]:
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [142]:
# np.random.normal(mean, std_dev, size=(4,2))

df = pd.DataFrame(np.random.rand(4, 2), # (4.2) is shape
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.612254  0.934177
  2  0.084548  0.708245
b 1  0.822177  0.437686
  2  0.644465  0.364417

In [143]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}

pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [144]:
# Explicit MultiIndex constructors

# creating a Multi Index from arrays

pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [145]:
# creating a Multi Index from tuples

pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [146]:
# creating a Multi Index from combinations of given values

pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [147]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]], codes=[[0, 0, 1, 1], [0, 1, 0, 1]])    

# in a book instead of codes, labels is used as an argument

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [148]:
# changing index names

pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [149]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])

# here a variable is created which is a combination of 2013 & 2014 and 1 & 2. 
# Here, 2013 & 2014 are year index, 1 & 2 are visit index

columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# The same approach but with subject, people's name and with their type, position

index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [150]:
columns

MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['subject', 'type'])

In [151]:
# mock some data
data = np.round(np.random.randn(4, 6), 1)
print(data)

# some math operations to change values

data[:, ::2] *= 10
data += 37

print('\n____________________________________\n')
print(data)

[[-1.2 -0.8  0.6 -1.2  1.5 -0.2]
 [ 1.1 -0.3  0.8 -1.1  0.6 -0.4]
 [-0.   0.9 -2.1  0.7 -0.3 -0.5]
 [ 1.6 -0.9  0.4  0.9 -0.7 -2.4]]

____________________________________

[[25.  36.2 43.  35.8 52.  36.8]
 [48.  36.7 45.  35.9 43.  36.6]
 [37.  37.9 16.  37.7 34.  36.5]
 [53.  36.1 41.  37.9 30.  34.6]]


In [152]:
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      25.0  36.2  43.0  35.8  52.0  36.8
     2      48.0  36.7  45.0  35.9  43.0  36.6
2014 1      37.0  37.9  16.0  37.7  34.0  36.5
     2      53.0  36.1  41.0  37.9  30.0  34.6

In [153]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      43.0  35.8
     2      45.0  35.9
2014 1      16.0  37.7
     2      41.0  37.9

In [154]:
# Go thoroughly by partitioning the whole code to see how to access a specific data values in a multi index

health_data['Guido', 'HR'].unstack()[2].iloc[0]

45.0

In [155]:
# Go thoroughly by partitioning the whole code to see how to access a specific data values in a multi index

health_data.unstack().unstack().unstack().loc['Bob'][2013].unstack().unstack().unstack()['HR'].iloc[0]

25.0

In [156]:
# to select several variables at once

health_data[['Guido', 'Bob']]

subject    Guido         Bob      
type          HR  Temp    HR  Temp
year visit                        
2013 1      43.0  35.8  25.0  36.2
     2      45.0  35.9  48.0  36.7
2014 1      16.0  37.7  37.0  37.9
     2      41.0  37.9  53.0  36.1

In [157]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [158]:
pop['California', 2000]

33871648

In [159]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [160]:
# to select several variables at once

pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [161]:
# a sign of : is required to show that you are taking all variable from this dimension. 
# In contrast to this, in R one can just omit to indicate this instead of using :

pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [162]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [163]:
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [164]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      25.0  36.2  43.0  35.8  52.0  36.8
     2      48.0  36.7  45.0  35.9  43.0  36.6
2014 1      37.0  37.9  16.0  37.7  34.0  36.5
     2      53.0  36.1  41.0  37.9  30.0  34.6

In [165]:
health_data['Guido', 'HR']

year  visit
2013  1        43.0
      2        45.0
2014  1        16.0
      2        41.0
Name: (Guido, HR), dtype: float64

In [166]:
health_data['Guido', 'HR'].iloc[0:2].unstack()

visit     1     2
year             
2013   43.0  45.0

In [167]:
# selecting several columns & rows at once

health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      25.0  36.2
     2      48.0  36.7

In [168]:
# selecting based on the variable names instead of Python built-in index numbers

health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        25.0
      2        48.0
2014  1        37.0
      2        53.0
Name: (Bob, HR), dtype: float64

#### The following 3 code chunks are so important as it demonstrates to access to data values using inside index

In [169]:
# Working with slices within these index tuples is not especially convenient; trying to
# create a slice within a tuple will lead to a syntax error:

# health_data.loc[(:, 1), (:, 'HR')]

print("""This following code gives an error: 

health_data.loc[(:, 1), (:, 'HR')] """)

This following code gives an error: 

health_data.loc[(:, 1), (:, 'HR')] 


In [170]:
# You could get around this by building the desired slice explicitly using Python’s built-in 
# slice() function, but a better way in this context is to use an IndexSlice object,
# which Pandas provides for precisely this situation. For example:

# WAY OF ACCESSING DATA USING INSIDE INDEX

idx = pd.IndexSlice
idx

In [171]:
# apply always before slicing, like
# dataset.loc[ idx[:,:], idx[:,:] ]

# WAY OF ACCESSING DATA USING INSIDE INDEX

health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      25.0  43.0  52.0
2014 1      37.0  16.0  34.0

#### Rearranging Multi-Indices

##### Sorted and unsorted indices

In [172]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]] #, names=['year', 'visit']
                                  )
data = pd.Series(np.random.rand(6), index=index)

# THIS FOLLOWING GIVES A NAME TO INDEX 
data.index.names = ['char', 'int']

data

char  int
a     1      0.388587
      2      0.904754
c     1      0.089460
      2      0.702699
b     1      0.847910
      2      0.085138
dtype: float64

In [173]:
# data['a':'b']

print('''If we try to take a partial slice of this index, it will result in an error:

data['a':'b']''')

If we try to take a partial slice of this index, it will result in an error:

data['a':'b']


In [174]:
index

MultiIndex([('a', 1),
            ('a', 2),
            ('c', 1),
            ('c', 2),
            ('b', 1),
            ('b', 2)],
           names=['char', 'int'])

Pandas provides a number of convenience routines to perform this type of sorting;
examples are the sort_index() and sortlevel() methods of the DataFrame.

In [175]:
# We have to run dataset.sort_index() so that we can later partion the data using index which is not possible earlier
# as it is in a form of tuple

data = data.sort_index()
data

char  int
a     1      0.388587
      2      0.904754
b     1      0.847910
      2      0.085138
c     1      0.089460
      2      0.702699
dtype: float64

In [176]:
# Now, thanks to the sort_index() we can partion the dataframe easily using index which was in a tuple form previously

data['a':'b']

char  int
a     1      0.388587
      2      0.904754
b     1      0.847910
      2      0.085138
dtype: float64

##### Stacking and unstacking indices

In [177]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [178]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [179]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [180]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### IMPORTANT: The next 3 code chunks

In [181]:
pop.unstack()

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [182]:
# this is kind of R codes: gather() and spread()

# the reverse of this in Python can be performed by applying multiindex functions OR set_index(), look at the next code chunk

pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [183]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

#### Data Aggregations on Multi-Indices: mean(), sum(), and max()

In [184]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      25.0  36.2  43.0  35.8  52.0  36.8
     2      48.0  36.7  45.0  35.9  43.0  36.6
2014 1      37.0  37.9  16.0  37.7  34.0  36.5
     2      53.0  36.1  41.0  37.9  30.0  34.6

In [185]:
data_mean = health_data.mean(level='year')
data_mean

C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\2845460446.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean = health_data.mean(level='year')


subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     36.5  36.45  44.0  35.85  47.5  36.70
2014     45.0  37.00  28.5  37.80  32.0  35.55

In [186]:
# The same code with different approach in an argument of index 

data_mean = health_data.mean(level=0)
data_mean

C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\3575556485.py:3: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean = health_data.mean(level=0)


subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     36.5  36.45  44.0  35.85  47.5  36.70
2014     45.0  37.00  28.5  37.80  32.0  35.55

In [187]:
data_mean = health_data.mean(level=1)
data_mean

C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\811502413.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean = health_data.mean(level=1)


subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
visit                                         
1        31.0  37.05  29.5  36.75  43.0  36.65
2        50.5  36.40  43.0  36.90  36.5  35.60

In [188]:
# Aggregating among different index levels

data_mean.mean(axis=1, level='type')

C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\2779220225.py:3: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean.mean(axis=1, level='type')


type          HR       Temp
visit                      
1      34.500000  36.816667
2      43.333333  36.300000

#### Combining Datasets: Merge and Join

In [189]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

print(df1); print('\n'); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [190]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

##### Many-to-one joins

In [191]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

print(df3); print('\n'); print(df4); print('\n'); print(pd.merge(df3, df4))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve


  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


##### Many-to-many joins

In [192]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})

print(df1); print('\n'); print(df5); print('\n'); print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization


  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization


In [193]:
# when the column names are the same

print(df1); print('\n'); print(df2); print('\n'); print(pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [194]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})

# when the column names are not the same

print(df1); print('\n'); print(df3); print('\n');
print(pd.merge(df1, df3, left_on="employee", right_on="name"))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000


  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000


In [195]:
# dropping a column called 'name', axis = 1 indicates to drop data column-wise 

pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

Sometimes, rather than merging on a column, you would instead like to merge on an index. For example, your data might look like this:

In [196]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

print(df1, '\n\n\n', df1a)
print('\n#########################\n')
print(df2, '\n\n\n', df2a)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 


                 group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

#########################

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 


           hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


You can use the index as the key for merging by specifying the left_index and/or right_index flags in pd.merge()

In [197]:
print(df1a); print('\n'); print(df2a); print('\n');
print(pd.merge(df1a, df2a, left_index=True, right_index=True))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR


          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014


In [198]:
# For convenience, DataFrames implement the join() method, which performs a merge that defaults to joining on indices:

print(df1a); print('\n'); print(df2a); print('\n'); print(df1a.join(df2a))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR


          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014


In [199]:
# If you’d like to mix indices and columns, you can combine left_index with right_on or left_on with right_index to get 
# the desired behavior:

print(df1a); print('\n'); print(df3); print('\n');
print(pd.merge(df1a, df3, left_index=True, right_on='name'))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR


   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000


         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000


In [200]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])

df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])


# By default, the result contains the intersection of the two sets of inputs; this is what is known as an inner join.

print(df6); print('\n'); print(df7); print('\n'); print(pd.merge(df6, df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread


     name drink
0    Mary  wine
1  Joseph  beer


   name   food drink
0  Mary  bread  wine


In [201]:
# We can specify this explicitly using the how keyword, which defaults to 'inner':

pd.merge(df6, df7, how='inner')

name   food drink
0  Mary  bread  wine

In [202]:
print(df6); print('\n'); print(df7); print('\n'); print(pd.merge(df6, df7, how='outer'))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread


     name drink
0    Mary  wine
1  Joseph  beer


     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer


In [203]:
print(df6); print('\n'); print(df7); print('\n'); print(pd.merge(df6, df7, how='left'))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread


     name drink
0    Mary  wine
1  Joseph  beer


    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine


In [204]:
print(df6); print('\n'); print(df7); print('\n'); print(pd.merge(df6, df7, how='right'))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread


     name drink
0    Mary  wine
1  Joseph  beer


     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer


In [205]:
# here as both df8 & df9 have the same column name - rank, a new dataframe will have to change new column names slightly by 
# adding suffixes

df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})

print(df8); print('\n'); print(df9); print('\n'); print(pd.merge(df8, df9, on="name"))

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4


   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2


   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2


In [206]:
print(df8); print('\n'); print(df9); print('\n');
print(pd.merge(df8, df9, on="name", suffixes=["_L", "_R"]))

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4


   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2


   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2


### Aggregation and Grouping: count(), sum(), mean(), median(), min(), and max()

In [207]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [208]:
ser.sum()

2.811925491708157

In [209]:
ser.mean()

0.5623850983416314

In [210]:
# A way of creating a dataframe

# pd.DataFrame({'column_name1': data, 'column_name2': data, ... })

df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
df

A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [211]:
df.mean()

A    0.477888
B    0.443420
dtype: float64

In [212]:
df.mean(axis=0)

A    0.477888
B    0.443420
dtype: float64

In [213]:
df.mean(axis='columns')

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [214]:
df.mean(axis=1)

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [215]:
# importing a dataset

import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [216]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [217]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

#### GroupBy: Split, Apply, Combine

In [218]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [219]:
df.groupby('key')

In [220]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [221]:
df.groupby('key').count()

data
key      
A       2
B       2
C       2

#### Column indexing

In [222]:
planets.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [223]:
planets.groupby('method')

In [224]:
planets.groupby('method')['orbital_period']

In [225]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [226]:
planets['method'].unique()

array(['Radial Velocity', 'Imaging', 'Eclipse Timing Variations',
       'Transit', 'Astrometry', 'Transit Timing Variations',
       'Orbital Brightness Modulation', 'Microlensing', 'Pulsar Timing',
       'Pulsation Timing Variations'], dtype=object)

#### Iteration over groups

In [227]:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)


In [228]:
for (method, group) in planets.groupby('method'):
    print(method, group)

Astrometry          method  number  orbital_period  mass  distance  year
113  Astrometry       1          246.36   NaN     20.77  2013
537  Astrometry       1         1016.00   NaN     14.98  2010
Eclipse Timing Variations                        method  number  orbital_period  mass  distance  year
32  Eclipse Timing Variations       1        10220.00  6.05       NaN  2009
37  Eclipse Timing Variations       2         5767.00   NaN    130.72  2008
38  Eclipse Timing Variations       2         3321.00   NaN    130.72  2008
39  Eclipse Timing Variations       2         5573.55   NaN    500.00  2010
40  Eclipse Timing Variations       2         2883.50   NaN    500.00  2010
41  Eclipse Timing Variations       1         2900.00   NaN       NaN  2011
42  Eclipse Timing Variations       1         4343.50  4.20       NaN  2012
43  Eclipse Timing Variations       2         5840.00   NaN       NaN  2011
44  Eclipse Timing Variations       2         1916.25   NaN       NaN  2011
Imaging        me

#### Dispatch methods

In [229]:
planets.groupby('method')['year'].describe()

count         mean       std     min      25%  \
method                                                                         
Astrometry                       2.0  2011.500000  2.121320  2010.0  2010.75   
Eclipse Timing Variations        9.0  2010.000000  1.414214  2008.0  2009.00   
Imaging                         38.0  2009.131579  2.781901  2004.0  2008.00   
Microlensing                    23.0  2009.782609  2.859697  2004.0  2008.00   
Orbital Brightness Modulation    3.0  2011.666667  1.154701  2011.0  2011.00   
Pulsar Timing                    5.0  1998.400000  8.384510  1992.0  1992.00   
Pulsation Timing Variations      1.0  2007.000000       NaN  2007.0  2007.00   
Radial Velocity                553.0  2007.518987  4.249052  1989.0  2005.00   
Transit                        397.0  2011.236776  2.077867  2002.0  2010.00   
Transit Timing Variations        4.0  2012.500000  1.290994  2011.0  2011.75   

                                  50%      75%     max  
method                                                  
Astrometry                     2011.5  2012.25  2013.0  
Eclipse Timing Variations      2010.0  2011.00  2012.0  
Imaging                        2009.0  2011.00  2013.0  
Microlensing                   2010.0  2012.00  2013.0  
Orbital Brightness Modulation  2011.0  2012.00  2013.0  
Pulsar Timing                  1994.0  2003.00  2011.0  
Pulsation Timing Variations    2007.0  2007.00  2007.0  
Radial Velocity                2009.0  2011.00  2014.0  
Transit                        2012.0  2013.00  2014.0  
Transit Timing Variations      2012.5  2013.25  2014.0

In [230]:
planets.groupby('method')['year'].describe().unstack()

       method                       
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...  
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

In [231]:
planets.groupby('method')['year'].describe().unstack()['max']

method
Astrometry                       2013.0
Eclipse Timing Variations        2012.0
Imaging                          2013.0
Microlensing                     2013.0
Orbital Brightness Modulation    2013.0
Pulsar Timing                    2011.0
Pulsation Timing Variations      2007.0
Radial Velocity                  2014.0
Transit                          2014.0
Transit Timing Variations        2014.0
dtype: float64

### Aggregate, filter, transform, apply

In [232]:
rng = np.random.RandomState(0)

df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1': range(6),
                   'data2': rng.randint(0, 10, 6)},
                  columns = ['key', 'data1', 'data2'])
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

**Aggregation.** We’re now familiar with GroupBy aggregations with sum(), median(),
and the like, but the aggregate() method allows for even more flexibility. It can take
a string, a function, or a list thereof, and compute all the aggregates at once. Here is a
quick example combining all these:

In [233]:
df.groupby('key').aggregate(['min', np.median, max])

data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [234]:
# Applying different operations to different columns

df.groupby('key').aggregate({'data1': 'min',
                             'data2': 'max'})

data1  data2
key              
A        0      5
B        1      7
C        2      9

**Filtering.** A filtering operation allows you to drop data based on the group proper‐
ties. For example, we might want to keep all groups in which the standard deviation is
larger than some critical value:

The filter() function should return a Boolean value specifying whether the group
passes the filtering. Here because group A does not have a standard deviation greater
than 4, it is dropped from the result

In [235]:
def filter_func(x):
    return x['data2'].std() > 4

In [236]:
print('print(df)'); print(df); print('\n'); print("print(df.groupby('key').std())"); print(df.groupby('key').std()); print('\n')
print("print(df.groupby('key').filter(filter_func))"); print(df.groupby('key').filter(filter_func))

print(df)
  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9


print(df.groupby('key').std())
       data1     data2
key                   
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641


print(df.groupby('key').filter(filter_func))
  key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9


**Transformation.** While aggregation must return a reduced version of the data, trans‐
formation can return some transformed version of the full data to recombine. For
such a transformation, the output is the same shape as the input. A common example
is to center the data by subtracting the group-wise mean:

In [237]:
df.groupby('key').transform(lambda x: x - x.mean())

data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

In [238]:
print(df.groupby('key').aggregate('mean'))

print('\n')
print(df)

     data1  data2
key              
A      1.5    4.0
B      2.5    3.5
C      3.5    6.0


  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9


**apply() method.** The apply() method lets you apply an arbitrary function to the
group results. The function should take a DataFrame, and return either a Pandas
object (e.g., DataFrame, Series) or a scalar; the combine operation will be tailored to
the type of output returned.

In [239]:
def norm_by_data2(x):
    # x is a DataFrame of group values
    x['data1'] /= x['data2'].sum()
    return x

In [240]:
print(df); print('\n'); 
print(df.groupby('key').apply(norm_by_data2))

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9


  key     data1  data2
0   A  0.000000      5
1   B  0.142857      0
2   C  0.166667      3
3   A  0.375000      3
4   B  0.571429      7
5   C  0.416667      9


C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\3182182404.py:2: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use 

	>>> .groupby(..., group_keys=True)
  print(df.groupby('key').apply(norm_by_data2))


In [241]:
print(df); print('\n'); 
print(df.groupby('key', group_keys = False).apply(norm_by_data2))

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9


  key     data1  data2
0   A  0.000000      5
1   B  0.142857      0
2   C  0.166667      3
3   A  0.375000      3
4   B  0.571429      7
5   C  0.416667      9


In [242]:
print(df); print('\n'); 
print(df.groupby('key', group_keys = True).apply(norm_by_data2))

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9


      key     data1  data2
key                       
A   0   A  0.000000      5
    3   A  0.375000      3
B   1   B  0.142857      0
    4   B  0.571429      7
C   2   C  0.166667      3
    5   C  0.416667      9


### IMPORTANT: Specifying the split key

##### 1. A list, array, series, or index providing the grouping keys

In [243]:
# manually controlling groupby() function depending on the wish

L = [0, 1, 0, 1, 2, 0]

print(df); print('\n'); print(df.groupby(L).sum())

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9


   data1  data2
0      7     17
1      4      3
2      4      7


C:\Users\azizt\AppData\Local\Temp\ipykernel_3924\486336292.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(df); print('\n'); print(df.groupby(L).sum())


In [244]:
print(df); print('\n'); print(df.groupby(df['key']).sum())

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9


     data1  data2
key              
A        3      8
B        5      7
C        7     12


##### 2. A dictionary or series mapping index to group

In [245]:
df2 = df.set_index('key')

mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonant'}

print(df2); print('\n'); print(df2.groupby(mapping).sum())

     data1  data2
key              
A        0      5
B        1      0
C        2      3
A        3      3
B        4      7
C        5      9


           data1  data2
key                    
consonant     12     19
vowel          3      8


##### 3. Any Python function

In [246]:
print(df2); print('\n'); print(df2.groupby(str.lower).mean())

     data1  data2
key              
A        0      5
B        1      0
C        2      3
A        3      3
B        4      7
C        5      9


     data1  data2
key              
a      1.5    4.0
b      2.5    3.5
c      3.5    6.0


In [247]:
print(df2); print('\n'); print(df2.groupby('key').mean())

     data1  data2
key              
A        0      5
B        1      0
C        2      3
A        3      3
B        4      7
C        5      9


     data1  data2
key              
A      1.5    4.0
B      2.5    3.5
C      3.5    6.0


##### 4. A list of valid keys

In [248]:
# adding another key

df2.groupby([str.lower, mapping]).mean()

data1  data2
key key                    
a   vowel        1.5    4.0
b   consonant    2.5    3.5
c   consonant    3.5    6.0

##### Grouping example

In [249]:
decade = 10 * (planets['year'] // 10)
decade = decade.astype(str) + 's'
decade.name = 'decade'

In [250]:
planets.groupby(['method', decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0

#### Pivot Tables

In [251]:
titanic = sns.load_dataset('titanic')

In [252]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

##### --- Pivot Tables by Hand ---

In [253]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [254]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack().round(4)

class    First  Second   Third
sex                           
female  0.9681  0.9211  0.5000
male    0.3689  0.1574  0.1354

##### --- Pivot Table Syntax --- 

#### The aggfunc keyword controls what type of aggregation is applied, which is a mean by default

In [255]:
titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

##### --- Multilevel pivot tables ---

#### IMPORTANT: We’ll bin the age using the pd.cut function:

In [256]:
age = pd.cut(titanic['age'], [0, 18, 80])

In [257]:
titanic.pivot_table('survived', ['sex', age], 'class').round(4)

class             First  Second   Third
sex    age                             
female (0, 18]   0.9091  1.0000  0.5116
       (18, 80]  0.9730  0.9000  0.4237
male   (0, 18]   0.8000  0.6000  0.2157
       (18, 80]  0.3750  0.0714  0.1337

In [258]:
# We can apply this same strategy when working with the columns as well; let’s add info
# on the fare paid using pd.qcut to automatically compute quantiles:



# The pd.qcut() function is used to perform quantile-based discretization of a continuous variable into equal-sized bins or 
# quantiles. The second argument specifies the number of quantiles to create. For example, if you set it to 2, it will
# create two quantiles, dividing the data into two equal-sized bins. If you set it to 4, it will create four quantiles, 
# dividing the data into four equal-sized bins, and so on.

fare = pd.qcut(titanic['fare'], 2)

titanic.pivot_table('survived', ['sex', age], [fare, 'class'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First   
sex    age                                                               
female (0, 18]               NaN  1.000000  0.714286          0.909091   
       (18, 80]              NaN  0.880000  0.444444          0.972973   
male   (0, 18]               NaN  0.000000  0.260870          0.800000   
       (18, 80]              0.0  0.098039  0.125000          0.391304   

fare                                 
class              Second     Third  
sex    age                           
female (0, 18]   1.000000  0.318182  
       (18, 80]  0.914286  0.391304  
male   (0, 18]   0.818182  0.178571  
       (18, 80]  0.030303  0.192308

# call signature as of Pandas 0.18: Documentation
#### DataFrame.pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')

In [259]:
#### Aggregating / Pivoting several questions / columns at the same time

titanic.pivot_table(index='sex', columns='class',
                    aggfunc={'survived':sum, 'fare':'mean'})

fare                       survived             
class        First     Second      Third    First Second Third
sex                                                           
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [260]:
# At times it’s useful to compute totals along each grouping. This can be done via the margins keyword:
# In other words, to add a column & row All to indicate total at the margins: margins = True

titanic.pivot_table('survived', index='sex', columns='class', margins=True)

class      First    Second     Third       All
sex                                           
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

In [261]:
# Calculating percentiles

# quartiles = np.percentile(births['births'], [25, 50, 75])

# Here, a dataset is births, a column births is a number of born babies in each year

# births_by_date.index = [pd.datetime(2012, month, day)
#                         for (month, day) in births_by_date.index]

# here, pay attention to the structure of the code so as to create a new index, indicating time: year/month/date

# births_by_date.head()                # PAGE: 177

# Out[21]: 
# 2012-01-01 4009.225
# 2012-01-02 4247.400
# 2012-01-03 4500.900
# 2012-01-04 4571.350
# 2012-01-05 4603.625
# Name: births, dtype: float64

### Vectorized String Operations

In [262]:
x = np.array([2, 3, 5, 7, 11, 13])
x * 2

array([ 4,  6, 10, 14, 22, 26])

In [263]:
data = ['peter', 'Paul', 'MARY', 'gUIDO']

# IMPORTANT: CODE STRUCTURE

# [FINAL OUTPUT CODE for i in data]
[s.capitalize() for s in data]

['Peter', 'Paul', 'Mary', 'Guido']

In [264]:
print("""If there is None value, then the code gives an error back. The following code does not run, due to the None value:

data = ['peter', 'Paul', None, 'MARY', 'gUIDO']
[s.capitalize() for s in data]
 """)

If there is None value, then the code gives an error back. The following code does not run, due to the None value:

data = ['peter', 'Paul', None, 'MARY', 'gUIDO']
[s.capitalize() for s in data]
 


In [265]:
names = pd.Series(data)
names

0    peter
1     Paul
2     MARY
3    gUIDO
dtype: object

In [266]:
names.str.capitalize()

0    Peter
1     Paul
2     Mary
3    Guido
dtype: object

In [267]:
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
                   'Eric Idle', 'Terry Jones', 'Michael Palin'])
monte

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
3         Eric Idle
4       Terry Jones
5     Michael Palin
dtype: object

In [268]:
monte.str.lower()

0    graham chapman
1       john cleese
2     terry gilliam
3         eric idle
4       terry jones
5     michael palin
dtype: object

In [269]:
monte.str.len()

0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [270]:
monte.str.startswith('T')

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [271]:
monte.str.split()

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
dtype: object

#### Methods using regular expressions

Table 3-4. Mapping between Pandas methods and functions in Python’s re module

Table 3-5. Other Pandas string methods

In [272]:
monte.str.extract('([A-Za-z]+)')

0
0   Graham
1     John
2    Terry
3     Eric
4    Terry
5  Michael

In [273]:
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')

0    [Graham Chapman]
1                  []
2     [Terry Gilliam]
3                  []
4       [Terry Jones]
5     [Michael Palin]
dtype: object

##### Vectorized item access and slicing.

In [274]:
monte.str[0:3]

0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: object

In [275]:
monte.str.split().str.get(-1)

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
dtype: object

**Indicator variables.** Another method that requires a bit of extra explanation is the
get_dummies() method. This is useful when your data has a column containing some
sort of coded indicator. For example, we might have a dataset that contains information in the form of codes, 
such as A=“born in America,” B=“born in the United Kingdom,” C=“likes cheese,” D=“likes spam”:

The get_dummies() routine lets you quickly split out these indicator variables into a
DataFrame:

In [276]:
full_monte = pd.DataFrame({'name': monte,
                           'info': ['B|C|D', 'B|D', 'A|C', 'B|D', 'B|C',
                                    'B|C|D']})
full_monte

name   info
0  Graham Chapman  B|C|D
1     John Cleese    B|D
2   Terry Gilliam    A|C
3       Eric Idle    B|D
4     Terry Jones    B|C
5   Michael Palin  B|C|D

In [277]:
full_monte['info'].str.get_dummies('|')

A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  0  1  0  1
4  0  1  1  0
5  0  1  1  1

In [278]:
# Here, pay attention to the implementation of regex function to find a list element that contains breakfast/Breakfast

# recipes.description.str.contains('[Bb]reakfast').sum()
# recipes.ingredients.str.contains('[Cc]innamon').sum()

### Working with Time Series

• **Time stamps** reference particular moments in time (e.g., July 4th, 2015, at 7:00
a.m.)

• **Time intervals** and **periods** reference a length of time between a particular begin‐
ning and end point—for example, the year 2015. Periods usually reference a spe‐
cial case of time intervals in which each interval is of uniform length and does
not overlap (e.g., 24 hour-long periods constituting days)

• **Time deltas** or **durations** reference an exact length of time (e.g., a duration of
22.56 seconds)

In [279]:
from datetime import datetime
datetime(year=2015, month=7, day=4)

datetime.datetime(2015, 7, 4, 0, 0)

In [280]:
# Or, using the dateutil module, you can parse dates from a variety of string formats:

from dateutil import parser
date = parser.parse("4th of July, 2015")
date

datetime.datetime(2015, 7, 4, 0, 0)

In [281]:
# Once you have a datetime object, you can do things like printing the day of the week:

date.strftime('%A')

'Saturday'

In [282]:
# The datetime64 dtype encodes dates as 64-bit integers, and thus allows arrays of dates to be represented very compactly. 
# The datetime64 requires a very specific input format:

date = np.array('2015-07-04', dtype=np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

In [283]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [284]:
date + np.arange(12)

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
      dtype='datetime64[D]')

In [285]:
# NumPy will infer the desired unit from the input; for example, here is a day-based datetime:

np.datetime64('2015-07-04')

numpy.datetime64('2015-07-04')

In [286]:
# Here is a minute-based datetime:

np.datetime64('2015-07-04 12:00')

numpy.datetime64('2015-07-04T12:00')

In [287]:
# Notice that the time zone is automatically set to the local time on the computer executing the code. You can force any 
# desired fundamental unit using one of many format codes; for example, here we’ll force a nanosecond-based time:

np.datetime64('2015-07-04 12:59:59.50', 'ns')

numpy.datetime64('2015-07-04T12:59:59.500000000')

#### Table 3-6. Description of date and time codes

In [288]:
np.datetime64('2015-07-04 12:59:59.50', 'Y')

numpy.datetime64('2015')

In [289]:
np.datetime64('2015-07-04 12:59:59.50', 'M')

numpy.datetime64('2015-07')

In [290]:
np.datetime64('2015-07-04 12:59:59.50', 'h')

numpy.datetime64('2015-07-04T12','h')

In [291]:
date = pd.to_datetime("4th of July, 2015")
date

Timestamp('2015-07-04 00:00:00')

In [292]:
date.strftime('%A')

'Saturday'

#### IMPORTANT

In [293]:
pd.to_timedelta(np.arange(12), 'D')

TimedeltaIndex([ '0 days',  '1 days',  '2 days',  '3 days',  '4 days',
                 '5 days',  '6 days',  '7 days',  '8 days',  '9 days',
                '10 days', '11 days'],
               dtype='timedelta64[ns]', freq=None)

In [294]:
date + pd.to_timedelta(np.arange(12), 'D')

DatetimeIndex(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
               '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
               '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
              dtype='datetime64[ns]', freq=None)

#### Pandas Time Series: Indexing by Time

In [295]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04',
                          '2015-07-04', '2015-08-04'])
data = pd.Series([0, 1, 2, 3], index=index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [296]:
data['2014-07-04':'2015-07-04']

2014-07-04    0
2014-08-04    1
2015-07-04    2
dtype: int64

In [297]:
data['2015']

2015-07-04    2
2015-08-04    3
dtype: int64

In [298]:
# Different approaches to input time data 

dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015',
                        '2015-Jul-6', '07-07-2015', '20150708'])
dates

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[ns]', freq=None)

In [299]:
dates.to_period('D')

PeriodIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
             '2015-07-08'],
            dtype='period[D]')

In [300]:
# Substracting date from date -> data2(2023/04/23) - data1(2021/11/04)

dates - dates[0]

TimedeltaIndex(['0 days', '1 days', '3 days', '4 days', '5 days'], dtype='timedelta64[ns]', freq=None)

In [301]:
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [302]:
# Alternatively, the date range can be specified not with a start- and endpoint, but with a startpoint and a number of periods:

pd.date_range('2015-07-03', periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [303]:
# You can modify the spacing by altering the freq argument, which defaults to D. For example, here 
# we will construct a range of hourly timestamps:


pd.date_range('2015-07-03', periods=8, freq='H')

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='H')

In [304]:
pd.period_range('2015-07', periods=8, freq='M')

PeriodIndex(['2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
             '2016-01', '2016-02'],
            dtype='period[M]')

In [305]:
pd.period_range('2015-07', periods=8, freq='Y')

PeriodIndex(['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'], dtype='period[A-DEC]')

In [306]:
# A sequence of durations increasing by an hour:

pd.timedelta_range(0, periods=10, freq='H')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[ns]', freq='H')

#### Table 3-7. Listing of Pandas frequency codes
#### Table 3-8. Listing of start-indexed frequency codes

In [307]:
pd.timedelta_range(0, periods=9, freq="2H30T")

TimedeltaIndex(['0 days 00:00:00', '0 days 02:30:00', '0 days 05:00:00',
                '0 days 07:30:00', '0 days 10:00:00', '0 days 12:30:00',
                '0 days 15:00:00', '0 days 17:30:00', '0 days 20:00:00'],
               dtype='timedelta64[ns]', freq='150T')

In [308]:
# All of these short codes refer to specific instances of Pandas time series offsets, which can be found in the 
# pd.tseries.offsets module. For example, we can create a business day offset directly as follows:

from pandas.tseries.offsets import BDay

pd.date_range('2015-07-01', periods=5, freq=BDay())

DatetimeIndex(['2015-07-01', '2015-07-02', '2015-07-03', '2015-07-06',
               '2015-07-07'],
              dtype='datetime64[ns]', freq='B')

#### SO IMPORTANT: Resampling, Shifting, and Windowing ---- PAGE: 196 - 208

#### High-Performance Pandas: eval() and query()

In [309]:
rng = np.random.RandomState(42)

x = rng.rand(1000000)
y = rng.rand(1000000)

In [310]:
# As discussed in “Computation on NumPy Arrays: Universal Functions” on page 50, 
# this is much faster than doing the addition via a Python loop or comprehension:

%timeit x + y

3.08 ms ± 58 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [311]:
%timeit np.fromiter((xi + yi for xi, yi in zip(x, y)), dtype=x.dtype, count=len(x))

202 ms ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [312]:
x

array([0.37454012, 0.95071431, 0.73199394, ..., 0.41807198, 0.42867126,
       0.92944855])

In [313]:
y

array([0.59515562, 0.36471714, 0.00537562, ..., 0.68311082, 0.33865907,
       0.69161641])

In [314]:
mask = (x > 0.5) & (y < 0.5)
mask

array([False,  True,  True, ..., False, False, False])

In [315]:
tmp1 = (x > 0.5)
tmp1

array([False,  True,  True, ..., False, False,  True])

In [316]:
tmp2 = (y < 0.5)
tmp2

array([False,  True,  True, ..., False,  True, False])

In [317]:
mask = tmp1 & tmp2
mask

array([False,  True,  True, ..., False, False, False])

In [318]:
import numexpr

In [319]:
mask_numexpr = numexpr.evaluate('(x > 0.5) & (y < 0.5)')
mask_numexpr

array([False,  True,  True, ..., False, False, False])

In [320]:
np.allclose(mask, mask_numexpr)

True

**numpy.allclose**: numpy.allclose is a function in the NumPy library in Python that compares two arrays element-wise for similarity within a certain tolerance. It returns True if all the corresponding elements of the two arrays are close enough (i.e., within the specified tolerance), and False otherwise.

### pandas.eval() for Efficient Operations

In [321]:
nrows, ncols = 100000, 100

rng = np.random.RandomState(42)

df1, df2, df3, df4 = (pd.DataFrame(rng.rand(nrows, ncols))
                      for i in range(4))

In [322]:
df1

0         1         2         3         4         5         6   \
0      0.374540  0.950714  0.731994  0.598658  0.156019  0.155995  0.058084   
1      0.031429  0.636410  0.314356  0.508571  0.907566  0.249292  0.410383   
2      0.642032  0.084140  0.161629  0.898554  0.606429  0.009197  0.101472   
3      0.051682  0.531355  0.540635  0.637430  0.726091  0.975852  0.516300   
4      0.103124  0.902553  0.505252  0.826457  0.320050  0.895523  0.389202   
...         ...       ...       ...       ...       ...       ...       ...   
99995  0.071979  0.439323  0.188588  0.586705  0.640611  0.662409  0.318503   
99996  0.313411  0.010490  0.469216  0.600825  0.451085  0.496918  0.983128   
99997  0.560873  0.647396  0.043068  0.282439  0.042950  0.346690  0.954034   
99998  0.710115  0.067999  0.611329  0.136199  0.054724  0.018160  0.911428   
99999  0.116834  0.461155  0.754556  0.250272  0.864631  0.588966  0.358260   

             7         8         9   ...        90        91        92  \
0      0.866176  0.601115  0.708073  ...  0.119594  0.713245  0.760785   
1      0.755551  0.228798  0.076980  ...  0.093103  0.897216  0.900418   
2      0.663502  0.005062  0.160808  ...  0.030500  0.037348  0.822601   
3      0.322956  0.795186  0.270832  ...  0.990505  0.412618  0.372018   
4      0.010838  0.905382  0.091287  ...  0.455657  0.620133  0.277381   
...         ...       ...       ...  ...       ...       ...       ...   
99995  0.600419  0.609742  0.390592  ...  0.122887  0.491140  0.032855   
99996  0.422056  0.719077  0.045588  ...  0.072444  0.715574  0.300257   
99997  0.603182  0.447768  0.888498  ...  0.880079  0.508377  0.442052   
99998  0.762005  0.245312  0.891027  ...  0.249632  0.894231  0.342761   
99999  0.655541  0.946702  0.145819  ...  0.298095  0.496018  0.990856   

             93        94        95        96        97        98        99  
0      0.561277  0.770967  0.493796  0.522733  0.427541  0.025419  0.107891  
1      0.633101  0.339030  0.349210  0.725956  0.897110  0.887086  0.779876  
2      0.360191  0.127061  0.522243  0.769994  0.215821  0.622890  0.085347  
3      0.776413  0.340804  0.930757  0.858413  0.428994  0.750871  0.754543  
4      0.188121  0.463698  0.353352  0.583656  0.077735  0.974395  0.986211  
...         ...       ...       ...       ...       ...       ...       ...  
99995  0.567250  0.428673  0.421092  0.021024  0.398596  0.405897  0.869783  
99996  0.087290  0.130703  0.549202  0.287877  0.589258  0.516884  0.254370  
99997  0.621332  0.314942  0.131085  0.697310  0.111705  0.397560  0.988347  
99998  0.844330  0.659797  0.835561  0.117920  0.211202  0.931760  0.296913  
99999  0.368719  0.837910  0.244971  0.061637  0.933295  0.245149  0.388890  

[100000 rows x 100 columns]

In [323]:
%timeit df1 + df2 + df3 + df4

69.4 ms ± 2.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [324]:
%timeit pd.eval('df1 + df2 + df3 + df4')

30.5 ms ± 784 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [325]:
np.allclose(df1 + df2 + df3 + df4,
            pd.eval('df1 + df2 + df3 + df4'))

True

In [326]:
df1, df2, df3, df4, df5 = (pd.DataFrame(rng.randint(0, 1000, (100, 3)))
                           for i in range(5))

In [327]:
df1

0    1    2
0   180  112  748
1   447  205  487
2   656  100   98
3    90  450  613
4   529  224  530
..  ...  ...  ...
95   31  787  643
96  984  624  352
97  283  543  751
98    5  142  278
99  258  662  895

[100 rows x 3 columns]

In [328]:
# Arithmetic operators

result1 = -df1 * df2 / (df3 + df4) - df5
result2 = pd.eval('-df1 * df2 / (df3 + df4) - df5')

np.allclose(result1, result2)

True

In [329]:
# Comparison operators

result1 = (df1 < df2) & (df2 <= df3) & (df3 != df4)
result2 = pd.eval('df1 < df2 <= df3 != df4')

np.allclose(result1, result2)

True

In [330]:
# Bitwise operators: pd.eval() supports the & and | bitwise operators:

result1 = (df1 < 0.5) & (df2 < 0.5) | (df3 < df4)
result2 = pd.eval('(df1 < 0.5) & (df2 < 0.5) | (df3 < df4)')

np.allclose(result1, result2)

True

In [331]:
# In addition, it supports the use of the literal and and or in Boolean expressions:

result3 = pd.eval('(df1 < 0.5) and (df2 < 0.5) or (df3 < df4)')

np.allclose(result1, result3)

True

In [332]:
# Object attributes and indices: pd.eval() supports access to object attributes via the obj.attr syntax, and 
# indexes via the obj[index] syntax:

result1 = df2.T[0] + df3.iloc[1]
result2 = pd.eval('df2.T[0] + df3.iloc[1]')

np.allclose(result1, result2)

True

In [333]:
# Other operations. Other operations, such as function calls, conditional statements, loops, and other more involved 
# constructs, are currently not implemented in pd.eval(). If you’d like to execute these more complicated types of 
# expressions, you can use the Numexpr library itself.

#### DataFrame.eval() for Column-Wise Operations

In [334]:
df = pd.DataFrame(rng.rand(1000, 3), columns=['A', 'B', 'C'])
df.head()

A         B         C
0  0.375506  0.406939  0.069938
1  0.069087  0.235615  0.154374
2  0.677945  0.433839  0.652324
3  0.264038  0.808055  0.347197
4  0.589161  0.252418  0.557789

In [335]:
result1 = (df['A'] + df['B']) / (df['C'] - 1)
result2 = pd.eval("(df.A + df.B) / (df.C - 1)")
 
np.allclose(result1, result2)

True

In [336]:
# The DataFrame.eval() method allows much more succinct evaluation of expressions with the columns:

result3 = df.eval('(A + B) / (C - 1)')

np.allclose(result1, result3)

True

In [337]:
df.head()

A         B         C
0  0.375506  0.406939  0.069938
1  0.069087  0.235615  0.154374
2  0.677945  0.433839  0.652324
3  0.264038  0.808055  0.347197
4  0.589161  0.252418  0.557789

In [338]:
# We can use df.eval() to create a new column 'D' and assign to it a value computed from the other columns:

df.eval('D = (A + B) / C', inplace=True)
df.head()

A         B         C          D
0  0.375506  0.406939  0.069938  11.187620
1  0.069087  0.235615  0.154374   1.973796
2  0.677945  0.433839  0.652324   1.704344
3  0.264038  0.808055  0.347197   3.087857
4  0.589161  0.252418  0.557789   1.508776

In [339]:
# In the same way, any existing column can be modified:

df.eval('D = (A - B) / C', inplace=True)
df.head()

A         B         C         D
0  0.375506  0.406939  0.069938 -0.449425
1  0.069087  0.235615  0.154374 -1.078728
2  0.677945  0.433839  0.652324  0.374209
3  0.264038  0.808055  0.347197 -1.566886
4  0.589161  0.252418  0.557789  0.603708

## IMPORTANT: Local variables in DataFrame.eval()
#### The DataFrame.eval() method supports an additional syntax that lets it work with local Python variables. Consider the following:

The @ character here marks a variable name rather than a column name. Notice that this @ character is only
supported by the DataFrame.eval() method, not by the pandas.eval() function,
because the pandas.eval() function only has access to the one (Python) namespace.

In [340]:
column_mean = df.mean(1)
result1 = df['A'] + column_mean

# LOOK AT THE CODE AND THE USE OF @
result2 = df.eval('A + @column_mean')
 
np.allclose(result1, result2)

True

#### DataFrame.query() Method

In [341]:
result1 = df[(df.A < 0.5) & (df.B < 0.5)]
result2 = pd.eval('df[(df.A < 0.5) & (df.B < 0.5)]')

np.allclose(result1, result2)

True

In [342]:
result2 = df.query('A < 0.5 and B < 0.5')

np.allclose(result1, result2)

True

In [343]:
result2

A         B         C         D
0    0.375506  0.406939  0.069938 -0.449425
1    0.069087  0.235615  0.154374 -1.078728
7    0.406639  0.128631  0.160742  1.729526
8    0.020236  0.354904  0.067919 -4.927445
16   0.110796  0.100477  0.561988  0.018362
..        ...       ...       ...       ...
984  0.154935  0.096410  0.795801  0.073542
985  0.126921  0.443428  0.859320 -0.368322
988  0.381958  0.058112  0.917827  0.352839
994  0.132644  0.472306  0.778643 -0.436223
995  0.082646  0.036840  0.439733  0.104169

[231 rows x 4 columns]

#### Note that the query() method also accepts the @ flag to mark local variables:

In [344]:
Cmean = df['C'].mean()
result1 = df[(df.A < Cmean) & (df.B < Cmean)]
 
result2 = df.query('A < @Cmean and B < @Cmean')

np.allclose(result1, result2)

True